name: 'Setup AWS Credentials'
description: 'Sets up AWS credentials for GitHub Actions'
inputs:
  aws_region:
    description: 'AWS Region'
    required: true
    type: string
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
    type: string
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
    type: string
  aws_session_token:
    description: 'AWS Session Token'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Create AWS credentials files
      shell: bash
      run: |
        mkdir -p $HOME/.aws
        echo "Directory created: $HOME/.aws"
        ACCOUNT_ID="test"
        PROFILE_NAME="${ACCOUNT_ID}_landg-administrator"
        {
          echo "[default]"
          echo "aws_access_key_id=${{ inputs.aws_access_key_id }}"
          echo "aws_secret_access_key=${{ inputs.aws_secret_access_key }}"
          echo "aws_session_token=${{ inputs.aws_session_token }}"
          echo "[$PROFILE_NAME]"
          echo "aws_access_key_id=${{ inputs.aws_access_key_id }}"
          echo "aws_secret_access_key=${{ inputs.aws_secret_access_key }}"
          echo "aws_session_token=${{ inputs.aws_session_token }}"
        } >> $HOME/.aws/credentials
        cat <<EOT >> $HOME/.aws/config
        [default]
        region = ${{ inputs.aws_region }}
        EOT
        echo "AWS credentials files created."
