name: Terraform Plan & Apply for AWS Accounts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - test
          - blah
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
  release:
    types:
      - released

jobs:
  setup-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: ./.github/actions/setup-aws-credentials
        with:
          aws_region: "e"
          aws_access_key_id: eeee
          aws_secret_access_key: fffff
          aws_session_token: fff

      - name: Check AWS credentials
        run: |
          echo "Checking AWS credentials..."
          ls -l $HOME/.aws/
          cat $HOME/.aws/credentials
          cat $HOME/.aws/config
          echo "${{ env.ENVIRONMENT }}"
          echo ${{ env.ENVIRONMENT }}
          terraform workspace new test
          terraform workspace new ${{ env.ENVIRONMENT }}

  another-job:
    runs-on: ubuntu-latest
    needs: setup-aws-credentials
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - name: Setup AWS Credentials
        uses: ./.github/actions/setup-aws-credentials
        with:
          aws_region: "e"
          aws_access_key_id: eeee
          aws_secret_access_key: fffff
          aws_session_token: fff
  
      - name: Check AWS credentials
        run: |
          echo "Checking AWS credentials..."
          ls -l $HOME/.aws/
          cat $HOME/.aws/credentials
          cat $HOME/.aws/config

# jobs:
  # run-terraform:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       environment: [dev, preprod, prod]
  #       include:
  #         - environment: preprod
  #           needs: run-terraform-dev
  #         - environment: prod
  #           needs: run-terraform-preprod
  #   needs: ${{ matrix.needs }}
  #   permissions:
  #     id-token: write
  #     contents: read
  #     pull-requests: write
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: Git checkout
  #     - name: test env
  #       run: |
  #         echo "Hello world"
  #         echo ${{ matrix.environment }}
